"""Node visitor for mod nodes."""

from __future__ import annotations

import ast
from typing import TYPE_CHECKING

from rubberize._exceptions import RubberizeNotImplementedError
from rubberize.latexer.visitors import StmtVisitor

if TYPE_CHECKING:
    from rubberize.latexer.stmt_latex import StmtLatex


# pylint: disable=invalid-name
class ModVisitor(ast.NodeVisitor):
    """Node visitor for ast.mod nodes.

    Each visitor method returns a list[StmtLatex] for the node.
    """

    def __init__(self, ns: dict[str, object] | None = None) -> None:
        super().__init__()
        self.ns = ns

    # pylint: disable-next=useless-parent-delegation
    def visit(self, node: ast.AST) -> list[StmtLatex]:
        return super().visit(node)

    def generic_visit(self, node: ast.AST) -> list[StmtLatex]:
        """Called if no visitor method is defined for a node."""

        raise RubberizeNotImplementedError(
            f"Unsupported ast.mod node: {type(node).__name__!r}"
        )

    def visit_Module(self, node: ast.Module) -> list[StmtLatex]:
        """Visit an AST generated by ast.parse() in exec mode."""

        return StmtVisitor(self.ns).visit_body(node.body)

    def visit_Expression(self, node: ast.Expression) -> list[StmtLatex]:
        """Visit an AST generated by ast.parse() in eval mode."""

        return StmtVisitor(self.ns).visit_body([ast.Expr(node.body)])

    def visit_Interactive(self, node: ast.Interactive) -> list[StmtLatex]:
        """Visit an AST generated by ast.parse() in single mode."""

        return StmtVisitor(self.ns).visit_body(node.body)
