---
title: Collections
toc: true
---

```{python}
%reload_ext rubberize
from rubberize.config import config
```

## Lists

Lists are rendered with Python syntax:

```{python}
%%tap
[]
[1.23, 4.56, 7.89]
[[1, 2], [3, 4]]
```

Unpacking is rendered as a union:

```{python}
%%tap
a = [1, 2]
[4, 5, *a]
```

### Aligning Vertically

If the list is longer than `@max_inline_elts`, it will be arranged vertically for readability.

```{python}
config.max_inline_elts
```

```{python}
%%tap
[1, 2, 3, 4, 5, 6]
```

### As an Array

`@show_list_as_array` controls the rendering style:

```{python}
config.show_list_as_array
```

 If set to `True`, lists will be rendered to look like an array, if possible:

```{python}
%%tap @show_list_as_array=True
[]
[1.23, 4.56, 7.89]
[[1, 2], [3, 4]]
```

1D list-arrays can be shown as a column vector by setting `@show_1d_as_col=True`

```{python}
%%tap @show_list_as_array=True @show_1d_as_col=True
[1.23, 4.56, 7.89]
```

`@array_delimiter` controls the appearance of delimiters used in a list-array. Use `"pmatrix"` for parentheses and `"bmatrix"` for square brackets.

```{python}
config.array_delimiter
```

```{python}
%%tap @show_list_as_array=True @array_delimiter="pmatrix"
[]
[1.23, 4.56, 7.89]
[[1, 2], [3, 4]]
```

### List Element Access

List element access appears as a subscript:

```{python}
%%tap
v = [1, 2, 3, 4]

v[0]   # Single element access
v[:2]  # Slice access
```

Whether or not the subscript is enclosed in parentheses is controlled by `@wrap_indices`:

```{python}
config.wrap_indices
```

```{python}
%%tap @wrap_indices=False
v = [1, 2, 3, 4]

v[0]   # Single element access
v[:2]  # Slice access
```

## List Comprehensions

List comprehensions are rendered like so:

```{python}
%%tap
a = [1, 2, 3, 4]
x = 3  # x is shadowed by the comprehension scope

[x**2 for x in a if x % 2 == 0]
```

## Tuples

Tuples are rendered with Python syntax:

```{python}
%%tap
()
(1.23, 4.56, 7.89)
((1, 2), (3, 4))
```

Unpacking is rendered as a union:

```{python}
%%tap
a = (1, 2)
(4, 5, *a)
```

### Aligning Vertically

If the tuple is longer than `@max_inline_elts`, it will be arranged vertically for readability.

```{python}
config.max_inline_elts
```

```{python}
%%tap
(1, 2, 3, 4, 5, 6)
```

### As an Array

`@show_tuple_as_array` controls the rendering style:

```{python}
config.show_tuple_as_array
```

 If set to `True`, tuples will be rendered to look like an array, if possible:

```{python}
%%tap @show_tuple_as_array=True
()
(1.23, 4.56, 7.89)
((1, 2), (3, 4))
```

1D tuple-arrays can be shown as a column vector by setting `@show_1d_as_col=True`

```{python}
%%tap @show_tuple_as_array=True @show_1d_as_col=True
(1.23, 4.56, 7.89)
```

`@array_delimiter` also controls the appearance of delimiters used in a tuple-array. Use `"pmatrix"` for parentheses and `"bmatrix"` for square brackets.

### Tuple Element Access

Tuple element access appears as a subscript:

```{python}
%%tap
v = (1, 2, 3, 4)

v[-1]   # Single element access
v[1:3]  # Slice access
```

Whether or not the subscript is enclosed in parentheses is controlled by `@wrap_indices`.

```{python}
%%tap @wrap_indices=False
v = (1, 2, 3, 4)

v[-1]   # Single element access
v[1:3]  # Slice access
```

## Sets

Sets are rendered with Python syntax:

```{python}
%%tap
set()
{1.23, 4.56, 7.89}
```

Unpacking is rendered as a union:

```{python}
%%tap
a = {1, 2}
{4, 5, *a}
```

### Aligning Vertically

If the set is longer than `@max_inline_elts`, it will be arranged vertically for readability.

```{python}
config.max_inline_elts
```

```{python}
%%tap
{1, 2, 3, 4, 5, 6}
```

## Set Comprehensions

Set comprehensions are rendered like so:

```{python}
%%tap
a = {1, 2, 3, 4}
x = 3  # x is shadowed by the comprehension scope

{x**2 for x in a if x % 2 == 0}
```

## Dictionaries

Dictionary objects are rendered like so:

```{python}
%%tap
{}
{"a": 1, "b": 2, "c": 3}
{1: 7.89, 2: 4.56, 3: 1.23}
```

Unpacking is rendered as a union:

```{python}
%%tap @stack
b = {"c": 3}
{"a": 1, "b": 2, **b}
```

### Aligning Vertically

If the dictionary is longer than `@max_inline_elts`, it will be arranged vertically for readability.

```{python}
config.max_inline_elts
```

```{python}
%%tap
{"a": 1, "b": 2, "c": 3, "d": 4, "e": 5, "f": 6}
```

### Dictionary Element Access

The dictionary element access appears as a subscript:

```{python}
%%tap
dct = {"a": 1, "b": 2, "c": 3}
dct["a"]
```

Whether or not the subscript is enclosed in parentheses is controlled by `@wrap_indices`.

```{python}
%%tap @wrap_indices=False
dct = {"a": 1, "b": 2, "c": 3}
dct["a"]
```

## Dictionary Comprehensions

Dictionary comprehensions are rendered like so:

```{python}
%%tap
a = [1, 2, 3, 4]
x = 3  # x is shadowed by the comprehension scope

{x: x**2 for x in a if x % 2 == 0} 
```
